### ISSUE TITLE
Pkts/s MaxTX AND tx_good_packets shows different numbers

### ISSUE THREAD

**Issue by syeedhaiderali** [pktgen/Pktgen-DPDK#72] opened 2021-05-26 11:04 UTC
We are allocating 1 RX Lcore and 4 TX lcore:  
$ sudo ./Builddir/app/pktgen -l 1,3,5,7,9,11 -n 4 --proc-type auto --log-level 7 --file-prefix pg -a 85:00.0 --socket-mem 0,8192 -- -T -P -m [3:5/7/9/11].0 -f themes/black-yellow.theme

When we start the test then Pkts/s Max TX are 69902304:
![image](https://user-images.githubusercontent.com/20606725/119646694-e25b1c80-be38-11eb-846c-95f562e58d5a.png)

But when we switch to "page xstats" then Pkts/s Max TX increases to 87018816 which was the numbers from tx_good_packets:  
![image](https://user-images.githubusercontent.com/20606725/119649616-43d0ba80-be3c-11eb-8241-500284d7de10.png)

![image](https://user-images.githubusercontent.com/20606725/119649677-55b25d80-be3c-11eb-8d47-279cc3638491.png)

Here are the questions that 
1) What is the actual rate? 
2) From where you are getting these numbers?

**Comment by pktgen** [comment] 2021-05-26 13:58
I can not see the 87Mpps in the second screen shot in my email, but do see it here in github, very strange.

The actual rate will be the number on the main page. I do not understand why the xstats reports something different, I will have to look at this one.

All of the numbers come from the NIC hardware or DPDK PMD code for that NIC. Pktgen only displays the values and attempts to give Mpps rate values.

**Comment by syeedhaiderali** [comment] 2021-06-14 06:40
Have you looked at the code why these numbers are different?

**Comment by pktgen** [comment] 2022-04-16 20:24
This issue may be caused by multiple threads updating counter a race condition. Please have a look at the latest 'dev' branch changes to see if this fixes the problem.

**Comment by KeithWiles** [comment] 2022-05-01 15:14
Please look at #104 should be fixed in the latest release.

**Closed as completed by KeithWiles** 2022-05-01 15:14 UTC
